### ISSUE TITLE
Why is the implementation of Relationship Extraction Module inconsistent with the description in the paper?

### ISSUE THREAD

**Issue by WenjinW** [PaddlePaddle/VIMER#10]
First of all, thank you for sharing this amazing work!
I encountered some confusion while reading the code and hope the author can answer it. I am very grateful for that.
The description of the Relationship Extraction Module in the paper is as follows:
![image](https://user-images.githubusercontent.com/30342227/154793614-41e27fd0-be72-4320-bcd1-8e83ac4d3ac9.png)

However, the implementation in https://github.com/PaddlePaddle/VIMER/blob/main/StrucTexT/external/linking/modules/model.py#L101 is as follows and which is a linear transformation of the absolute value of the difference between the features of the two nodes.
![image](https://user-images.githubusercontent.com/30342227/154792136-f531cb4c-9746-451d-a995-56ca69ffe2c0.png)
Is there any special consideration here?
Thanks again to the author for your reading and help!

**Comment by linan142857** [comment]
Thanks for your question.

This release is an upgraded version of the paper, including the code and results.

After the paper was published, we continued to make experiments on StrucTexT. We further found that the model with parameters would reduce the performance of linking tasks on small datasets (FUNSD).

Therefore, we carried out parameter-free optimization for linking modeling.

**Comment by WenjinW** [comment]
Thank you for your answer!
