### ISSUE TITLE
Entity linking scores significantly better than the number

### ISSUE THREAD

**Issue by liaohaofu** [PaddlePaddle/VIMER#16]
Hi, I noticed that your FUNSD entity linking scores reported in this repo. are higher than the number in the paper. For example, "StrucTexT-chn&eng base" is 0.7045 and "StrucTexT-eng base (paper)" is 0.4410. Could you let me know what contributes to the improvement here? Or is anything wrong with the original paper's approach? Thanks!

**Comment by linan142857** [comment]
The public version has introduced upgrades to the original paper in three main points:

1. More datas is used for pretraining (11 million vs 1 million).
2. We use the results of entity labeling to support the entity linking, which can alleviate data imbalance.
3. Spatial relationship bias is introduced in our attention module.
