### ISSUE TITLE
Unable to download pretrained model artifact

### ISSUE THREAD

**Issue by kkkris7** [PaddlePaddle/VIMER#3]
Hi, I am trying to test the inference but I am not able to download pretrained model artifact. Could you please verify the link of it? Thanks!

**Comment by linan142857** [comment]
The download is blocked by "Mixed Content" and we have fixed it.Thanks for your suggestions.

**Comment by linan142857** [comment]
The download is blocked by "Mixed Content" and we have fixed it.
Thanks for your suggestions.
