### ISSUE TITLE
StrucText V2跑不起来啊，好多bug

### ISSUE THREAD

**Issue by NLPOR** [PaddlePaddle/VIMER#32]
在v2中运行下面脚本出现好多问题
python -u ./tools/eval.py     --config_file=configs/end2end_ocr/ocr_funsd_base.json     --task_type=end2end_ocr     --label_path=./data/funsd/dataset/testing_data/otations     --image_path=./data/funsd/dataset/testing_data/images     --weights_path=StrucTexT_v2_end2end_ie_base.pdparams
1.  模块缺失
from tasks.text_spotting_db.recg_head import RecgHead
from tasks.text_spotting_db.dataset import LabelConverter
text_spotting_db 找遍了整个仓库都没有名字不对，应该是
from tasks.end2end_ocr.recg_head import RecgHead
from tasks.end2end_ocr.dataset import LabelConverter 
2. 代码缺失
Traceback (most recent call last):
  File "./tools/eval.py", line 103, in <module>
    eval(config)
  File "./tools/eval.py", line 87, in eval
    model = Model(model_config, eval_config['feed_names'])
  File "/home/xiaxy/VIMER/StrucTexT/v2/src/tasks/end2end_ocr/model.py", line 150, in __init__
    self.db_loss = DBLoss()
NameError: name 'DBLoss' is not defined
同样没有找到DBLoss()的定义，不知道代码是否完整啊，怎么跑这个推理？？？？？

**Comment by linan142857** [comment]
十分抱歉，相关的bug已经修复了，您可以push之后再试一下
