### ISSUE TITLE
在 aistudio.baidu.com 中测试 StrucTexT v2.0，无法下载 RVL-CDIP文档图像分类 数据文件

### ISSUE THREAD

**Issue by KennyLeung** [PaddlePaddle/VIMER#38]
按照 https://aistudio.baidu.com/aistudio/datasetdetail/147611 创建项目，看到 data 已经预先存放 4 个模型文件，然后按照README 安装好 requirements， 当要下载 RVL-CDIP文档图像分类 文件时，不成功，看样子是由于文件存放在google docs 的原因，这类存放在无法下载网址的文件，官方可否事先存放在 aistudio.baidu.com 可下载的位置？

这个项目很贴近真实应用场景，非常有前景，但由于文档和示例缺失，感觉很难参与进来，希望官方重视这点。如果像PaddleOCR之类有完善的测试环境和详尽的文档的项目，参与者热情肯定高涨。迫切希望官方先在  aistudio.baidu.com 提供一个测试示例，感激不尽！

**Comment by RogerYu123** [comment]
由于版权原因，我们无法对数据进行二次发布，你可通过官方渠道或者[huggingface](https://huggingface.co/datasets/rvl_cdip)进行数据下载。
