### ISSUE TITLE
关于StrucText v2 中的table recognize的问题？

### ISSUE THREAD

**Issue by ganggang233** [PaddlePaddle/VIMER#47]
请问StrucText v2 中的table recognize中的link_up、link_down、link_left和link_right代表什么？
        link_up = link_probs[:, 0:1, :, :]
        link_down = link_probs[:, 1:2, :, :]
        link_left = link_probs[:, 2:3, :, :]
        link_right = link_probs[:, 3:4, :, :]
非常期待您的解答！

**Comment by RogerYu123** [comment]
分别为上下左右相邻最小分割单元格中的属于同一个单元格的概率

**Comment by ganggang233** [comment]
> 分别为上下左右相邻最小分割单元格中的属于同一个单元格的概率

非常感谢您的解答，能否给出v2/src/data/transform/ops/operators.py中 TableLabelEncode 函数中的输入数据data的数据结构样例，这将有助于我进一步理解这个算法的核心思想。

**Comment by RogerYu123** [comment]
> 

https://arxiv.org/abs/2208.14687 具体方案已公开，可参考这篇paper

**Comment by ganggang233** [comment]
> > 
> 
> https://arxiv.org/abs/2208.14687 具体方案已公开，可参考这篇paper

好的，非常感谢
