### ISSUE TITLE
structext什么时候公开训练代码？

### ISSUE THREAD

**Issue by aishangmaxiaoming** [PaddlePaddle/VIMER#5]

**Comment by RogerYu123** [comment]
Thanks for the suggestion. We will add the action item to the road map.

**Comment by aishangmaxiaoming** [comment]
> Thanks for the suggestion. We will add the action item to the road map.

非常期待，十分理解预训练暂时不公开，但是自己的数据训练一下也可以的，希望尝尝鲜，大概什么时间可以有训练流程呢？辛苦啦
