### ISSUE TITLE
Is there a plan to release the training script for the UFO models?

### ISSUE THREAD

**Issue by YangLiu14** [PaddlePaddle/VIMER#9]
First of all, thank you for sharing this amazing work!
I want to ask if you plan to release the training script for multi-task models? I'm most intrigued in details of how the models are trained.

**Comment by yellowjs0304** [comment]
me too.. Do you have any plans? @RogerYu123

**Comment by godson1024** [comment]
The training code have been released, please visit https://github.com/PaddlePaddle/VIMER/tree/main/UFO/OneForAll
